#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

#
# if the file in special_agents it will not work, don't now why, it looks in the wrong directory
#
# from cmk.special_agents.agent_cisco_ise import main
from cmk.special_agent.agent_checkmk_update import main

if __name__ == '__main__':
    main()
