#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# License: GNU General Public License v2
#
# Author: thl-cmk[at]outlook[dot]com
# URL   : https://thl-cmk.hopto.org
# Date  : 2021-12-18


def agent_checkmk_update(params, hostname, ipaddress):
    args = []

    if 'use-ipaddress' in params:
        args += ['--host', ipaddress]
    else:
        args += ['--host', hostname]

    if 'timeout' in params:
        args += ['--timeout', params['timeout']]

    return args


special_agent_info['checkmk_update'] = agent_checkmk_update
