#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.


def agent_cisco_ise_arguments(params, hostname, ipaddress):
    args = []

    if 'use-ipaddress' in params:
        args += ['--host', ipaddress]
    else:
        args += ['--host', hostname]

    if 'timeout' in params:
        args += ['--timeout', params['timeout']]

    return args


special_agent_info['checkmk_download'] = agent_cisco_ise_arguments
